resolver: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
packages:
  - '.'
  - location:
      git: git@github.com:Dridus/ghcjs-react.git
      commit: be1786c5b28de8693e48d1f86858f3863bc7980c
    extra-dep: true
extra-deps:
  - ghcjs-dom-0.2.3.1
  - monad-control-1.0.1.0
  - transformers-base-0.4.4
  - transformers-compat-0.5.1.4

